<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Entrar no Chat</title>

    <!-- Bootstrap core CSS -->
    <link href="<?= ROOT_URL ?>/assets/css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= ROOT_URL ?>/assets/css/login.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400' rel='stylesheet' type='text/css'>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
  <div id="back">
    <canvas id="canvas" class="canvas-back"></canvas>
      <div class="backRight">    
      </div>
      <div class="backLeft">
      </div>
  </div>
<div id="slideBox">
  <div class="topLayer">
    <div class="right">
      <div class="content">
            <h2>Preencha seus dados</h2>
            <form class="form-signin" method="POST" action="<?= $this->UrlBuilder()->doAction('login', ['init_user' => true]); ?>">
                <?php
                    $error = isset($this->params['error']) ? $this->params['error'] : false;

                    if ( $error ) :
                ?>
                        <p class="bg-danger"><?= htmlentities($error); ?></p>
                <?php endif; ?>
                <div class="form-element form-stack">
                <label for="inputNickname">Nickname</label>
                <input type="text" id="inputNickname" name="nickname" placeholder="Nickname" required autofocus>
                </div>
                <div class="form-element form-stack">
                <label for="inputEmail">E-mail</label>
                <input type="email" id="inputEmail" name="email" placeholder="E-mail" required>
                </div>
                <br />
                <button class="btn btn-lg btn-primary btn-block" type="submit">Bater Papo!</button>
            </form>
            </div>
        </div>
    </div>
</div>
        
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.11.3/paper-full.min.js'></script>
    <script  src="<?= ROOT_URL ?>/assets/js/tela.js"></script>
</body>
</html>
