<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title>EChat - Seu Canal de Bate Papo Online - Douglas Rangel WebMaster</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="<?= ROOT_URL ?>/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="<?= ROOT_URL ?>/assets/css/style.css" rel="stylesheet" />

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script>
        var Ajax = {
            url : '<?= ROOT_URL ?>'
        }
    </script>
    <script src="<?= ROOT_URL ?>/assets/js/jquery.js" defer></script>
    <script src="<?= ROOT_URL ?>/assets/js/moment.js" defer></script>
    <script src="<?= ROOT_URL ?>/assets/js/chat.js" defer></script>

</head>
<body style="font-family:Verdana">

<div class="container">

    <div class="row " style="padding-top:30px;">